export const NounsDescriptorABI = {
  address: '0x25fF2FdE7df1A433E09749C952f7e09aD3C27951',
  abi: [
    {
      inputs: [
        { internalType: 'contract INounsArt', name: '_art', type: 'address' },
        {
          internalType: 'contract ISVGRenderer',
          name: '_renderer',
          type: 'address',
        },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'BadPaletteLength', type: 'error' },
    { inputs: [], name: 'EmptyPalette', type: 'error' },
    { inputs: [], name: 'IndexNotFound', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'contract INounsArt',
          name: 'art',
          type: 'address',
        },
      ],
      name: 'ArtUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'string',
          name: 'baseURI',
          type: 'string',
        },
      ],
      name: 'BaseURIUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'bool', name: 'enabled', type: 'bool' },
      ],
      name: 'DataURIToggled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'previousOwner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newOwner',
          type: 'address',
        },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    { anonymous: false, inputs: [], name: 'PartsLocked', type: 'event' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'contract ISVGRenderer',
          name: 'renderer',
          type: 'address',
        },
      ],
      name: 'RendererUpdated',
      type: 'event',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'accessories',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'accessoryCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes', name: 'encodedCompressed', type: 'bytes' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addAccessories',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pointer', type: 'address' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addAccessoriesFromPointer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'string', name: '_background', type: 'string' }],
      name: 'addBackground',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes', name: 'encodedCompressed', type: 'bytes' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addBodies',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pointer', type: 'address' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addBodiesFromPointer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes', name: 'encodedCompressed', type: 'bytes' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addGlasses',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pointer', type: 'address' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addGlassesFromPointer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes', name: 'encodedCompressed', type: 'bytes' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addHeads',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pointer', type: 'address' },
        { internalType: 'uint80', name: 'decompressedLength', type: 'uint80' },
        { internalType: 'uint16', name: 'imageCount', type: 'uint16' },
      ],
      name: 'addHeadsFromPointer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'string[]', name: '_backgrounds', type: 'string[]' },
      ],
      name: 'addManyBackgrounds',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'arePartsLocked',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'art',
      outputs: [
        { internalType: 'contract INounsArt', name: '', type: 'address' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'backgroundCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'backgrounds',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'baseURI',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'bodies',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'bodyCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        {
          components: [
            { internalType: 'uint48', name: 'background', type: 'uint48' },
            { internalType: 'uint48', name: 'body', type: 'uint48' },
            { internalType: 'uint48', name: 'accessory', type: 'uint48' },
            { internalType: 'uint48', name: 'head', type: 'uint48' },
            { internalType: 'uint48', name: 'glasses', type: 'uint48' },
          ],
          internalType: 'struct INounsSeeder.Seed',
          name: 'seed',
          type: 'tuple',
        },
      ],
      name: 'dataURI',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'decompressor',
      outputs: [
        { internalType: 'contract IDecompressor', name: '', type: 'address' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'glassesCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'glasses',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'contract INounsArt', name: '_art', type: 'address' },
      ],
      name: 'setArt',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'string', name: '_baseURI', type: 'string' }],
      name: 'setBaseURI',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {
          internalType: 'contract IDecompressor',
          name: '_decompressor',
          type: 'address',
        },
      ],
      name: 'setDecompressor',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {
          internalType: 'contract ISVGRenderer',
          name: '_renderer',
          type: 'address',
        },
      ],
      name: 'setRenderer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bool', name: '_enabled', type: 'bool' }],
      name: 'setDataURIToggle',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'heads',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'headCount',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'indexToImage',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
      name: 'indexToSVG',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {
          internalType: 'contract ISVGRenderer',
          name: '_renderer',
          type: 'address',
        },
      ],
      name: 'setSVGRenderer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;
